name: denscord_fe
version: 1.0.0+1
publish_to: none
description: A tiny discord clone written in FastAPI and Flutter.
environment: 
  sdk: '^3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_bottom_navigation_bar: ^1.2.0
  overlapping_panels: ^0.0.3
  get_storage: ^2.1.1
  path_provider: ^2.0.15
  http: ^0.13.0
  cached_network_image: ^3.2.3
  timeago: ^3.4.0
  web_socket_channel: ^2.1.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: FixelDisplay
      fonts:
        - asset: assets/fonts/FixelDisplay-ExtraBold.ttf
          weight: 800
    - family: FixelText
      fonts:
        - asset: assets/fonts/FixelText-Bold.ttf
          weight: 700
        - asset: assets/fonts/FixelText-Medium.ttf
          weight: 500
        - asset: assets/fonts/FixelText-Regular.ttf
          weight: 400
        - asset: assets/fonts/FixelText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/FixelText-ExtraBold.ttf
          weight: 800

